### ISSUE TITLE
Fails to build in react-native@0.33 - Naming conflict

### ISSUE THREAD

**Issue by rgovindji** [VansonLeung/react-native-keyboard-aware-view#8]
I'm getting a naming conflict in react-native v0.33

```
ailed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: UIManagerTestModule
  Paths: /Users/rgovindji/Projects/Bunch/node_modules/react-native-keyboard-aware-view/node_modules/react-native/ReactAndroid/src/androidTest/js/UIManagerTestModule.js collides with /Users/rgovindji/Projects/Bunch/node_modules/react-native/ReactAndroid/src/androidTest/js/UIManagerTestModule.js

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: UIManagerTestModule
  Paths: /Users/rgovindji/Projects/Bunch/node_modules/react-native-keyboard-aware-view/node_modules/react-native/ReactAndroid/src/androidTest/js/UIManagerTestModule.js collides with /Users/rgovindji/Projects/Bunch/node_modules/react-native/ReactAndroid/src/androidTest/js/UIManagerTestModule.js

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (HasteMap.js:155:13)
    at HasteMap.js:115:31

```

**Comment by rgovindji** [comment]
I think this is because you have react-native as a dependency and a peer dependency 

```
  "dependencies": {
    "react-native": ">=0.13.0",
    "react-timer-mixin": "^0.13.3"
  },
  "peerDependencies": {
    "react-native": ">=0.13.0"
```
